name: lib_utils
description: 工具库
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # 获取当前设备的可用磁盘空间与磁盘总量 https://github.com/mboeddeker/disk_space
  disk_space: ^0.2.1
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^2.0.3
  # 基于事件总线的解耦方案 https://github.com/marcojakob/dart-event-bus
  event_bus: ^2.0.0
  # 启动URL行为（拨打电话、发送短信等） https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
  url_launcher: ^6.0.18
  # 跨平台html包（可以换回dart:html）https://github.com/dint-dev/universal_html
  universal_html: ^2.0.8
  #启用或禁用设备唤醒锁，多用于防止设备休眠 https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock
  wakelock: ^0.6.1+2
  # RSA、AES加密库 https://github.com/YourksChan/flutter_cipher
  flutter_cipher:
    git:
      url: https://github.com/FBSocial/flutter_cipher.git
      ref: 2.0.0
  # 日志记录插件，可以配置日志等级 https://github.com/dart-lang/logging
  logging: ^1.0.2
  # 多音频文件播放器(修改的原因是因为原播放器在播放的时候会强行切AVAUDIOSESSION) https://github.com/bluefireteam/audioplayers
  audioplayers:
    git:
      url: https://github.com/FBSocial/audioplayers.git
      path: packages/audioplayers
      ref: 7122f75cc3b7a939358080a68b1a35b9146b890f

  shared_preferences: ^2.0.15
  # 语法糖：元组实现 https://github.com/google/tuple.dart
  tuple: ^2.0.0
  # GetX轻量级的Flutter整体解决方案（状态管理、依赖注入和路由管理） https://github.com/jonataslaw/getx
  get:
    git:
      url: https://github.com/FBSocial/getx_fix.git
      ref: 4.6.5.2
  # 日期格式插件 https://github.com/tejainece/date_format
  date_format: ^2.0.5
  intl: ^0.17.0
  lib_net:
    path: ../lib_net

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
